# Generated by Django 6.0.2 on 2026-04-12 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films_catalog', '0004_alter_review_star_alter_review_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='film',
            field=models.ManyToManyField(to='films_catalog.film'),
        ),
    ]
